const webview={convertPixelToRem:function(fontSize){const BASE_FONT_SIZE=16;const value=fontSize/BASE_FONT_SIZE;return value;},getFontSize:function(computedFontSize,fontSizeDifferenceInPercentage){const value=computedFontSize-(fontSizeDifferenceInPercentage/100*computedFontSize);return value;},isFacebook:function(){var userAgent=navigator.userAgent||navigator.vendor||window.opera;return(userAgent.indexOf("FBAN")>-1)||(userAgent.indexOf("FBAV")>-1);},isInstagram:function(){var userAgent=navigator.userAgent||navigator.vendor||window.opera;return userAgent.match(/Instagram\ ([0-9\.]+)/);},isAndroid:function(){var userAgent=navigator.userAgent.toLowerCase();return userAgent.match("android");},getScale:function(getDifferenceInPercentage){if(getDifferenceInPercentage===-25){return getDifferenceInPercentage-36.5;}
if(getDifferenceInPercentage===-12.5){return getDifferenceInPercentage-13.5;}
if(getDifferenceInPercentage===0){return getDifferenceInPercentage}
if(getDifferenceInPercentage<6.25&&getDifferenceInPercentage>0){return getDifferenceInPercentage;}
if(getDifferenceInPercentage===6.25&&getDifferenceInPercentage<25){return getDifferenceInPercentage+8;}
if(getDifferenceInPercentage===25&&getDifferenceInPercentage<50){return getDifferenceInPercentage+15;}
if(getDifferenceInPercentage===50&&getDifferenceInPercentage<100){return getDifferenceInPercentage+5;}
if(getDifferenceInPercentage===68.75){return getDifferenceInPercentage+2;}
if(getDifferenceInPercentage===100){return getDifferenceInPercentage-10;}},adjustFontSize:function(){let getDifferenceInPercentage;const BASE_FONT_SIZE=16;const getComputedBodyFontSize=parseInt(window.getComputedStyle(document.body).fontSize);const getDifferenceBetweenBaseAndComputedFontSize=getComputedBodyFontSize-BASE_FONT_SIZE;getDifferenceInPercentage=(getDifferenceBetweenBaseAndComputedFontSize/BASE_FONT_SIZE*100);getDifferenceInPercentage=this.getScale(getDifferenceInPercentage);[...document.getElementsByClassName("widget-text")].forEach(element=>{const display=window.getComputedStyle(element).display;if(display==='none'){return;}
const getComputedElementFontSize=parseInt(window.getComputedStyle(element).fontSize);const setFontSize=this.getFontSize(getComputedElementFontSize,getDifferenceInPercentage);const convertFontSizeToRem=this.convertPixelToRem(setFontSize);element.style.fontSize=convertFontSizeToRem.toFixed(2)+'rem';})}};window.addEventListener('DOMContentLoaded',function(){if(webview.isFacebook()||webview.isInstagram()){if(webview.isAndroid()){webview.adjustFontSize();}}});